<a href="https://colab.research.google.com/github/DimasWerito/Math_01/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%BD%D1%96_%D0%B2%D0%BF%D1%80%D0%B0%D0%B2%D0%B8_%D0%BD%D0%B0_%D0%B7%D0%B0%D0%BD%D1%8F%D1%82%D1%82%D1%8F_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array([[1, 5, 3],[5, 1,2]])
print(A)

[[1 5 3]
 [5 1 2]]


In [2]:
import numpy as np
a = np.array([[1,1],[2,2],[3,3],[4,4],[5,5]])
b = np.array([[1,1,1],[2,2,2]])
print(a)
print(b)
total = a.dot(b)
print(total)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
[[1 1 1]
 [2 2 2]]
[[ 3  3  3]
 [ 6  6  6]
 [ 9  9  9]
 [12 12 12]
 [15 15 15]]


In [ ]:
import numpy as np
B = np.array([[1,2],[3,4]])
print(B)

[[1 2]
 [3 4]]


In [ ]:
import numpy as np
E = np.array([[3,1,1,1],[1,3,1,1],[1,1,3,1],[1,1,1,3]])
print(E)

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]]


In [ ]:
import numpy as np
F = np.array([[1,1,1,5],[1,1,5,1],[1,5,1,1],[5,1,1,1]])
print(F)

[[1 1 1 5]
 [1 1 5 1]
 [1 5 1 1]
 [5 1 1 1]]


In [ ]:
import numpy as np
G = np.array([[4,1,1,5],[0,4,5,1],[0,0,4,1],[0,0,0,4]])
print(G)

[[4 1 1 5]
 [0 4 5 1]
 [0 0 4 1]
 [0 0 0 4]]


In [ ]:
import numpy as np
H = np.array([[4,0,0,0],[4,4,0,0],[2,7,4,0],[1,-3,9,4]])
print(H)

[[ 4  0  0  0]
 [ 4  4  0  0]
 [ 2  7  4  0]
 [ 1 -3  9  4]]


In [ ]:
import numpy as np
A = np.array([[2,1,-1],[0,1,-4]])
B = np.array([[-2,1,0],[-3,2,2]])
print(A+B)

[[ 0  2 -1]
 [-3  3 -2]]


In [ ]:
import numpy as np
C = np.array([[1,2,2,2],[3,4,4,4]])
print(C)

[[1 2 2 2]
 [3 4 4 4]]


In [ ]:
import numpy as np
D = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(D)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
import numpy as np
A = np.array([[4,1,-1],[5,1,-4]])
B = np.array([[-2,3,0],[2,2,2]])
print(A + B)

[[ 2  4 -1]
 [ 7  3 -2]]


In [ ]:
import numpy as np
C = np.array([[4,1,-1],[-1,6,5],[5,1,-4]])
D = np.array([[-2,3,0],[8,1,7],[2,2,2]])
print(C + D)

[[ 2  4 -1]
 [ 7  7 12]
 [ 7  3 -2]]


In [ ]:
import numpy as np
A = np.array([[2,1,-1],[0,1,-4]])
print(3 * A)

[[  6   3  -3]
 [  0   3 -12]]


In [ ]:
import numpy as np
A = np.array([[2,1,-1],[0,1,-4]])
print(5 * A)

[[ 10   5  -5]
 [  0   5 -20]]


In [ ]:
import numpy as np
B = np.array([[7,1,-1],[2,3,-4]])
print(2 * B)

[[14  2 -2]
 [ 4  6 -8]]


In [ ]:
import numpy as np
C = np.array([[1,5,-1],[7,1,-1],[5,3,1]])
print(5 * C)

[[ 5 25 -5]
 [35  5 -5]
 [25 15  5]]


In [7]:
import numpy as np

def get_matrix_dimensions(matrix):
  num_rows, num_columns = matrix.shape
  return num_rows, num_columns
A = np.array([[2,0,0,1],[0,-1,2,1],[2,1,0,3]])
dimensions = get_matrix_dimensions(A)
print("Кількість строк:", dimensions[0])
print("Кількість стовпців:", dimensions[1])

Кількість строк: 3
Кількість стовпців: 4


In [8]:
import numpy as np
def get_matrix_dimensions(matrix):
  num_rows, num_columns = matrix.shape
  return num_rows, num_columns
B = np.array([[2,0],[0,-1],[2,1]])
dimensions = get_matrix_dimensions(B)
print("Кількість строк:", dimensions[0])
print("Кількість стовпців:", dimensions[1])

Кількість строк: 3
Кількість стовпців: 2


In [11]:
import numpy as np
def get_matrix_dimensions(matrix):
  num_rows, num_columns = matrix.shape
  return num_rows, num_columns
C = np.array([[2,0,0,1],[0,-1,2,1],[0,-1,2,1],[2,1,0,3],[2,0,0,1]])
dimensions = get_matrix_dimensions(C)
print("Кількість строк:", dimensions[0])
print("Кількість стовпців:", dimensions[1])

Кількість строк: 5
Кількість стовпців: 4


In [13]:


def generate_random_matrix(rows, columns, low_limit, high_limit):
  random_matrix = np.random.randint(low_limit, high_limit, size=(rows, columns))
  return random_matrix

rows = 5
columns = 5
low_limit = 1
high_limit = 10

random_matrix = generate_random_matrix(rows, columns, low_limit, high_limit)

print("Випадково заповнена матриця:")
print(random_matrix)


Випадково заповнена матриця:
[[2 7 8 8 8]
 [8 7 6 6 7]
 [1 2 6 9 5]
 [8 4 7 2 4]
 [4 4 6 4 5]]


In [14]:
import random
def gen_eye_matrix(row):
  return np.eye(row)

n = random.randint(1, 100)

eye_matrix = gen_eye_matrix(n)

print("Одиночна матриця:")
print(eye_matrix)

get_matrix_dimensions(eye_matrix)



Одиночна матриця:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


(84, 84)

In [17]:
import numpy as np
import random

def generate_reverse_diagonal_matrix(size):
  matrix = np.zeros((size, size), dtype=int)
  for i in range(size):
    matrix[size - i - 1, i] = random.randint(1, 10)
  return matrix

matrix_size = 5
result_matrix = generate_reverse_diagonal_matrix(matrix_size)
print("Матриця із заповненою лише зворотньою діагоналлю випадковими даними:")
print(result_matrix)

Матриця із заповненою лише зворотньою діагоналлю випадковими даними:
[[0 0 0 0 5]
 [0 0 0 6 0]
 [0 0 8 0 0]
 [0 7 0 0 0]
 [8 0 0 0 0]]


In [23]:
import numpy as np
import pandas as pd

matrixA = np.array([[1,3,-1],[0,1,-1],[1,1,2]])
matrixB = np.array([[1,-3,2],[-1,0,1],[2,1,1]])

dfA = pd.DataFrame(matrixA)
dfB = pd.DataFrame(matrixB)

dfA.to_csv('matrixA.csv', index=False, header=False)
dfB.to_csv('matrixB.csv', index=False, header=False)

def matrix_mul(A, B):
  if A.shape[1] != B.shape[0]:
    raise ValueError("Неможливо помножити ці матриці, кількість стовпців у А"
                      "повинна дорівнювати кількості рядків у В.")
  res = np.dot(A, B)
  return res

def matrix_add(A, B):
  if A.shape != B.shape:
    raise ValueError("Матриці мають різні розміри, додавання неможливе.")
  res = A + B
  return res

import pandas as pd

def get_matrix_eval(file_path1, file_path2):
  matrix1 = pd.read_csv(file_path1, header=None).values
  matrix2 = pd.read_csv(file_path2, header=None).values
  operation = input("Виберіть операцію(додавання, добуток, добуток_число):")
  if operation == 'додавання':
    result = matrix_add(matrix1, matrix2)
  elif operation =='добуток':
    result = matrix_mul(matrix1, matrix2)
  elif operation == 'добуток_число':
    coef = float(input("Введіть число для множення:"))
    result = coef * matrix1
  else:
    result = None
    print("Неправильна операція!")
  return result



res = get_matrix_eval('matrixA.csv', 'matrixB.csv')

if res is not None:
  print("Результат:")
  print(res)

Виберіть операцію(додавання, добуток, добуток_число):додавання
Результат:
[[ 2  0  1]
 [-1  1  0]
 [ 3  2  3]]


In [28]:
import numpy as np

examples = []

def generate_matrix_multiplication_examples(num_examples, matrix_size):
  for i in range(num_examples):
    matrix1 = np.random.randint(1, 10, size=(matrix_size, matrix_size))
    matrix2 = np.random.randint(1, 10, size=(matrix_size, matrix_size))
    product = np.dot(matrix1, matrix2)
    examples.append((matrix1, matrix2, product))
  return examples


examples = generate_matrix_multiplication_examples(5, 3)
for i, (matrix1, matrix2, product) in enumerate(examples, 1):
  print(f"Example #{i}:")
  print(f"Matrix1:\n{matrix1}")
  print(f"Matrix2:\n{matrix2}")
  print(f"Expected product:\n{product}\n")

Example #1:
Matrix1:
[[6 5 7]
 [8 7 7]
 [3 5 9]]
Matrix2:
[[8 1 8]
 [8 1 2]
 [8 8 4]]
Expected product:
[[144  67  86]
 [176  71 106]
 [136  80  70]]

Example #2:
Matrix1:
[[9 1 1]
 [3 3 8]
 [9 5 7]]
Matrix2:
[[6 3 7]
 [1 3 1]
 [4 8 2]]
Expected product:
[[59 38 66]
 [53 82 40]
 [87 98 82]]

Example #3:
Matrix1:
[[9 6 9]
 [4 5 4]
 [2 5 5]]
Matrix2:
[[9 7 1]
 [6 5 4]
 [1 3 4]]
Expected product:
[[126 120  69]
 [ 70  65  40]
 [ 53  54  42]]

Example #4:
Matrix1:
[[6 6 8]
 [1 7 8]
 [6 5 6]]
Matrix2:
[[5 5 9]
 [1 2 9]
 [7 1 9]]
Expected product:
[[ 92  50 180]
 [ 68  27 144]
 [ 77  46 153]]

Example #5:
Matrix1:
[[8 6 6]
 [4 5 4]
 [8 8 7]]
Matrix2:
[[8 8 8]
 [5 8 4]
 [9 4 6]]
Expected product:
[[148 136 124]
 [ 93  88  76]
 [167 156 138]]



In [ ]:
import numpy as np
import time

def generate_matrix_multiplication_example(matrix_size):
  matrix1 = np.random.randint(1, 10, size=(matrix_size, matrix_size))
  matrix2 = np.random.randint(1, 10, size=(matrix_size, matrix_size))
  product = np.dot(matrix1, matrix2)

  #Display the matrices and prompt the user to solve
  print(f"Solve the matrix multiplication:\n")
  print(f"Matrix 1:\n{matrix1}\n")
  print(f"Matrix 2:\n{matrix2}]n")

  #Record the start time
  start_time = time.time()

  #prompt user for the solution
  user_solution = input(f"Enter your solution for the product matrix(comma-separated row values):")
  user_solution = np.array(list(map(int, user_solution.split(",")))).reshape(matrix_size, matrix_size)

  #record the end time
  end_time = time.time()

  #check if the users solution is correct
  if np.array_equal(user_solution, product):
    print(f"\nCorrect!It took you{end_time - start_time:2f}seconds.")
  else:
    print(f"\nIncorrect. The correct product matrix is:\n{product}")


#Example of usage:
generate_matrix_multiplication_example(3)

Solve the matrix multiplication:

Matrix 1:
[[9 8 6]
 [6 2 8]
 [8 5 7]]

Matrix 2:
[[6 2 5]
 [7 2 1]
 [5 8 5]]]n
